name: CI
on: [push]

jobs:
  mac:
    name: Build (os=${{ matrix.os }}, llvm=${{ matrix.llvm }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-10.15', 'windows-2022']
        llvm: ['11.0.1']
    steps:
      - uses: actions/checkout@v1
      - run: ./main.sh
        shell: bash
        env:
          version: ${{ matrix.llvm }}
          threads: 2
      - uses: actions/upload-artifact@v2
        with:
          name: clang+llvm-${{ matrix.llvm }}-${{ matrix.os }}
          path: clang+llvm-${{ matrix.llvm }}-*.*
